services:
    novaway.alert_listener:
        class: Novaway\AdminBundle\EventListener\AlertListener
        arguments:
            - '@mailer'
            - '@translator'
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
