version: '2'
services:
    db:
        image: mysql:5.6
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    php:
        build:
            context: docker/php
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - .:/var/www/symfony
            - ./logs/php:/var/www/symfony/app/logs
    nginx:
        build: docker/nginx
        ports:
            - 80:80
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx

#    elasticsearch:
#        image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
#        environment:
#            - bootstrap.memory_lock=true
#            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#            - http.host=0.0.0.0
#            - transport.host=127.0.0.1
#        ulimits:
#            memlock:
#                soft: -1
#                hard: -1
#        ports:
#            - 9200:9200
#            - 9300:9300
#        volumes:
#            - "./.data/elasticsearch:/data"
#        volumes_from:
#          - php
#          - nginx
#        networks:
#              - esnet

#    kibana:
#        image: docker.elastic.co/kibana/kibana:6.3.1
#        environment:
#          - server.host=0.0.0.0
#          - elasticsearch.username=
#          - elasticsearch.password=
#    elk:
#        image: willdurand/elk
#        ports:
#            - 81:80
#        volumes:
#            - ./docker/elk/logstash:/etc/logstash
#            - ./docker/elk/logstash/patterns:/opt/logstash/patterns
#        volumes_from:
#            - php
#            - nginx

    mailcatcher:
       image: yappabe/mailcatcher
       ports:
           - 1025:1025
           - 1080:1080
