services:
    admin.book:
        class: Novaway\AdminBundle\Admin\BookAdmin
        arguments: [~, Novaway\CommonBundle\Entity\Book, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: entities.book.label, group: Articles }
        public: true

    admin.blueray:
        class: Novaway\AdminBundle\Admin\BluerayAdmin
        arguments: [~, Novaway\CommonBundle\Entity\Blueray, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: entities.blueray.label, group: Articles }
        public: true


    admin.dvd:
        class: Novaway\AdminBundle\Admin\DvdAdmin
        arguments: [~, Novaway\CommonBundle\Entity\Dvd, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: entities.dvd.label, group: Articles }
        public: true

    admin.actor:
        class: Novaway\AdminBundle\Admin\ActorAdmin
        arguments: [~, Novaway\CommonBundle\Entity\Actor, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: entities.actor.label, group: Personnes }
        public: true

    admin.director:
        class: Novaway\AdminBundle\Admin\DirectorAdmin
        arguments: [~, Novaway\CommonBundle\Entity\Director, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: entities.director.label, group: Personnes }
        public: true

    admin.author:
        class: Novaway\AdminBundle\Admin\AuthorAdmin
        arguments: [~, Novaway\CommonBundle\Entity\Author, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: entities.author.label, group: Personnes }
        public: true